name: ğŸ“¦ pkg.pr.new

on:
  # https://blog.esciencecenter.nl/reduce-reuse-recycle-save-the-planet-one-github-action-at-a-time-4ab602255c3f
  push:
    paths:
      - src/**
      - .gitignore
      - bunup.config.ts
      - package.json
      - biome.jsonc
      - bun.lock
      - tsconfig*.json
      - "!**/*.md"

  pull_request:
    paths:
      - src/**
      - .gitignore
      - bunup.config.ts
      - package.json
      - biome.jsonc
      - bun.lock
      - tsconfig*.json
      - "!**/*.md"

jobs:
  pkg-pr-new:
    name: âš¡ pkg.pr.new
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'okineadev/gitpaper'

    permissions: {}

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          sparse-checkout-cone-mode: false
          # Download only the necessary files
          sparse-checkout: |
            src/
            .gitignore
            bunup.config.ts
            package.json
            bun.lock
            README.md
            LICENSE
            tsconfig*.json

      - name: ğŸ”§ Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      - name: ğŸ“¦ Install dependencies
        run: bun ci

      - name: âš’ï¸ Build package
        run: bun run build

      - name: âš¡ Publish prerelease
        run: bunx pkg-pr-new publish --compact --bin
